version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9.2.0
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Testing
          command: docker-compose -f docker-compose-test.yml run docker-ci
  deploy:
    machine: ture // 把docker拔掉換成machine
    steps:
      - checkout
      - run:
          name: Install EB Command Line
          command: >
            sudo apt-get update &&
            sudo apt-get install -y python python-dev python-pip python-virtualenv &&
            sudo rm -rf /var/lib/apt/lists/* &&
            sudo pip install awsebcli &&
            sudo pip install --upgrade --user awsebcli
      - run:
          name: Setup EB Credentials
          command: >
            mkdir -p ~/.aws &&
            echo [default] >> ~/.aws/credentials &&
            echo aws_access_key_id = $AWS_ACCESS_KEY_ID >> ~/.aws/credentials &&
            echo aws_secret_access_key = $AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials
      - deploy:
          name: Deploy To ENV Staging
          #command: sudo eb deploy docker-ci-test-dev # deploy (Deploy to eb)
          command: eb deploy --profile default
workflows: 
  version: 2 
  docker-cicd: 
    jobs: 
      - test
      - deploy:
          requires:
            - test